# Generated by Django 5.0.2 on 2024-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
