# Generated by Django 5.0.2 on 2024-02-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airreport', '0006_alter_sensor_name_alter_sensor_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='airquaility',
            new_name='airquaility1',
        ),
        migrations.AddField(
            model_name='sensor',
            name='airquaility2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='airquaility3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 18, 30, 30, 867491)),
        ),
    ]
