# Generated by Django 5.0.2 on 2024-02-15 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airreport', '0008_alter_sensor_airquaility1_alter_sensor_airquaility2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 18, 34, 55, 475800)),
        ),
    ]
