# Generated by Django 5.0.2 on 2024-02-16 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airreport', '0010_alter_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 2, 28, 18, 797472)),
        ),
    ]
